services:
  apiGateway:
    build: .
    image: api-gateway:latest
    ports :
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://authService:4005
    networks:
      - internal

networks:
  internal:
    external: true
    name: shared-internal