services:
  BillingService:
    build: .
    image: billing-service:latest
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:
    external: true
    name: shared-internal