services:
  auth-service-db:
    image: postgres:latest
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authServiceDb
    networks:
      - internal
    volumes:
      - authServiceData:/var/lib/postgresql/data

  authService:
    depends_on:
      - auth-service-db
    build: .
    image: auth-service:latest
    # ports:
    #   - "4005:4005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/authServiceDb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: ZnVsbHlibHVlcHJvdmV0d2VudHlzdGFuZGFyZHNvb25zbGlnaHRseWJhbmR0ZXJyaWI=
    networks:
      - internal


volumes:
  authServiceData:

networks:
  internal:
    external: true
    name: shared-internal
